name: Feature as User Story
description: Write user-story from selected user perspective
title: "[Feature]: example of title"
labels: ["feature"]
# noinspection YAMLSchemaValidation
projects: [ "Progress-House/9"]

body:
  - type: markdown
    attributes:
      value: |
        please make sure you complete all required fields
  - type: dropdown
    id: role
    attributes:
      label: "User Story"
      description: "Select your role: user - client with account, guest - client without account, moderator - ofitoo app staff"
      options:
        - 'as a user'
        - 'as a guest'
        - 'as a moderator'
        - 'as a technical team member'

      default: 0
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: "-----------------------------------------------------------------"
      placeholder: "I would like to have new feature, when i do ... i want to have ..."
      description: "example: I would like the application to send me a confirmation email after making the payment"
    validations:
      required: true
  - type: textarea
    id: requirements
    attributes:
      label: "requirements: "
      value: "- [ ] include unit tests: when ... then ..."
    validations:
      required: true
  - type: textarea
    id: examples
    attributes:
      label: "docs / links / diagrams: "
      description: "sample implementation, documentation, links to YouTube, github for better understanding.."
    validations:
      required: false
  - type: textarea
    id: blocked
    attributes:
      label: "blocked by"
      description: "List any issues that this request depends on. Separate multiple issues with a comma ','"
      placeholder: https://github.com/Progress-House/ofitoo-backend/issues/1 , https://github.com/Progress-House/ofitoo-backend/issues/2
    validations:
      required: false
